"""Alerts generated by risk / movement agents (Telegram, EMR, dashboard)."""
from sqlalchemy import Column, Integer, String, Text, Float, ForeignKey, DateTime, Boolean
from datetime import datetime, timezone

from app.core.database import Base


class AlertSeverity(str):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("rehab_sessions.id"))
    patient_id = Column(Integer, ForeignKey("patients.id"))
    severity = Column(String(32), default=AlertSeverity.WARNING)
    type = Column(String(64))  # wrong_form / fatigue / compensation / safety
    message = Column(Text)
    score = Column(Float)
    evidence_clip_url = Column(String(256))
    acknowledged = Column(Boolean, default=False)
    delivered_telegram = Column(Boolean, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
