"use client";

import { Box, Grid, Stack, Typography, Chip, Button, Divider } from "@mui/material";
import { AutoAwesome, Download, NoteAdd, Warning, SyncProblem } from "@mui/icons-material";
import SectionCard from "@/components/common/SectionCard";
import GaugeRing from "@/components/common/GaugeRing";
import { reports, alerts, aiRecommendation } from "@/lib/mockData";

const sevColor: Record<string, string> = { critical: "#ef5b5b", warning: "#f5b73b", info: "#22d3ee" };

export default function ReportsPage() {
  return (
    <Box sx={{ maxWidth: 1500, mx: "auto" }}>
      <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", sm: "center" }} spacing={2} sx={{ mb: 3 }}>
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 800, letterSpacing: "-0.02em" }}>
            AI Reports & SOAP Notes
          </Typography>
          <Typography sx={{ color: "text.secondary", mt: 0.5 }}>
            Generated by SOAP Agent + therapist entries
          </Typography>
        </Box>
        <Stack direction="row" spacing={1}>
          <Button variant="outlined" startIcon={<NoteAdd />} sx={{ borderColor: "rgba(34,211,238,0.35)", color: "#22d3ee" }}>New SOAP</Button>
          <Button variant="contained" startIcon={<AutoAwesome />}>Generate Auto Report</Button>
        </Stack>
      </Stack>

      <Grid container spacing={2.5}>
        <Grid item xs={12} lg={8}>
          <SectionCard title="Generated Reports" subtitle="SOAP Agent + therapist entries">
            <Stack spacing={1.5}>
              {reports.map((r) => (
                <Box key={r.id} className="glass-card-compact" sx={{ p: 1.5 }}>
                  <Stack direction="row" justifyContent="space-between" alignItems="center">
                    <Box>
                      <Typography variant="body2" sx={{ fontWeight: 700 }}>{r.patient}</Typography>
                      <Typography variant="caption" sx={{ color: "text.secondary" }}>{r.date} · {r.type}</Typography>
                    </Box>
                    <Stack direction="row" spacing={1} alignItems="center">
                      <Chip label={`Q ${r.quality}`} size="small" sx={{ bgcolor: "rgba(34,211,238,0.12)", color: "#22d3ee" }} />
                      <Chip label={r.risk} size="small" sx={{ bgcolor: sevColor[r.risk === "High" ? "critical" : "warning"] + "22", color: sevColor[r.risk === "High" ? "critical" : "warning"] }} />
                      <Button size="small" startIcon={<Download />} sx={{ color: "#22d3ee" }}>FHIR</Button>
                    </Stack>
                  </Stack>
                  <Typography variant="caption" sx={{ color: "text.secondary", display: "block", mt: 0.5 }}>Plan: {r.plan}</Typography>
                </Box>
              ))}
            </Stack>
          </SectionCard>
        </Grid>

        <Grid item xs={12} lg={4}>
          <Stack spacing={2.5}>
            <SectionCard title="Therapist Assistant" subtitle="Decision summary">
              <Stack direction="row" justifyContent="space-around" sx={{ mb: 1 }}>
                <GaugeRing value={aiRecommendation.riskScore} size={96} thickness={8} label="Risk" color="#f5b73b" />
                <GaugeRing value={aiRecommendation.movementScore} size={96} thickness={8} label="Quality" color="#22d3ee" />
              </Stack>
              <Typography variant="body2" sx={{ color: "text.secondary" }}>{aiRecommendation.recommendation}</Typography>
            </SectionCard>

            <SectionCard title="Active Alerts" subtitle="Risk Agent outputs">
              <Stack spacing={1}>
                {alerts.map((a) => (
                  <Box key={a.id} className="glass-card-compact" sx={{ p: 1.2, borderLeft: `3px solid ${sevColor[a.severity]}` }}>
                    <Stack direction="row" spacing={1} alignItems="center">
                      {a.severity === "critical" ? <Warning sx={{ color: sevColor[a.severity], fontSize: 16 }} /> : <SyncProblem sx={{ color: sevColor[a.severity], fontSize: 16 }} />}
                      <Typography variant="body2" sx={{ fontWeight: 700 }}>{a.patient}</Typography>
                      <Chip label={a.type} size="small" sx={{ ml: "auto", height: 18, fontSize: 10, bgcolor: sevColor[a.severity] + "22", color: sevColor[a.severity] }} />
                    </Stack>
                    <Typography variant="caption" sx={{ color: "text.secondary" }}>{a.msg}</Typography>
                  </Box>
                ))}
              </Stack>
            </SectionCard>
          </Stack>
        </Grid>
      </Grid>
    </Box>
  );
}
